################## 系统配置 ##################

# 搜索
search:
  provider: "local" # 搜索提供引擎， local / external / none
  path: # 搜索生成的文件的路径
    page: search
    index_file: search-index.json
  includes:  # 搜索包含的内容
    - post
    - page
  content: true # 包含文章和页面的内容

################## 样式配置 ##################

# 图片配置
image:
  favicon: "/hc/assets/favicon.png" # 站点图标
  avatar: "https://avatars.githubusercontent.com/u/98081672?v=4" # 个人信息挂件上的头像
  banner:
    light: "https://dev.krt.moe/demo-assets/banner.webp"
    dark: "https://dev.krt.moe/demo-assets/banner_dark.webp"
  background:
    light: "https://dev.krt.moe/demo-assets/bg.webp"
    dark: "https://dev.krt.moe/demo-assets/bg.webp"
  about: # 介绍卡片
      light: "https://dev.krt.moe/demo-assets/banner.webp" # 亮色模式
      dark: "https://dev.krt.moe/demo-assets/banner.webp" # 暗色模式

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 时间轴
      icon: archive
      url: /archives/
    - label: 快速开始
      icon: book
      url: /posts/beginner-course/software/
    - label: 汇川视觉
      icon: book
      submenu:
        - label: 入门教程
          icon: book
          url: /categories/汇川视觉/入门课程/
        - label: 中级教程
          icon: book
          url: /categories/汇川视觉/中级教程/
        - label: 高级教程
          icon: book
          url: /categories/汇川视觉/高级教程/
    - label: 海康视觉
      icon: book
      url: https://blog.drfengling.online/hk
    - label: VisionPro视觉
      icon: book
      url: http://blog.drfengling.online/VisionProvideostudydoc/
    - label: 音乐
      icon: music
      url: http://music.drfengling.online/
    - label: 图片
      icon: photo
      url: http://imgdb.drfengling.online/
    - label: AI
      icon: magic
      submenu:
        - label: GPT4o-mini
          icon: magic
          url: https://lobechat.drfengling.online
        - label: GPT3.5
          icon: magic
          url: https://a.drfengling.online
        - label: 爱豆在线问答
          icon: magic
          url: https://idol.drfengling.online
        - label: 与大模型聊天
          icon: magic
          url: https://chat.drfengling.online
        - label: 微笑脸
          icon: magic
          url: https://model.drfengling.online  
    - label: 链接
      icon: link
      submenu:
        - label: 代码仓库
          icon: code
          url: https://github.com/drfengyu/hc
    - label: 留言板
      icon: comment
      url: /posts/site-build/lyb
        
posts:
  default_cover: "/hc/images/default.webp" # 没有头图的文章使用的默认图片 https://dev.krt.moe/demo-assets/banner.webp
  donate: true # 默认是否启用打赏功能
  share: true # 默认是否启用分享功能
  word_count: # 字数统计功能
    enable: true # 是否启用
    threshold: 1500 # 超过多少字开始显示为千字
    estimate_wavy: true # 在千字的约数前显示波浪号

# Footer 页脚配置
footer:
  links:
    - icon: github
      link: https://github.com/drfengyu
    - icon: rss
      link: /hc/atom.xml
  components:
    uptime:
      since: "2024/09/05 17:03:12"
      text: "本站已在风雨中飘摇"
    author:
      homepage: "https://github.com/drfengyu"
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://github.io" target="_blank">Github Pages</a> 暖心托管

# 代码高亮
# syntax_highlighter:
#   theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "QQ"
      icon: "qq"
      color: "#00bfff"
      link: "https://connect.qq.com/widget/shareqq/index.html?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "QQ空间"
      icon: "star"
      color: "#fece00"
      link: "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "微博"
      icon: "weibo"
      color: "#e6162d"
      link: "https://service.weibo.com/share/share.php?url=$URL&title=$TITLE"
#     - name: "X"
#       html: |
#         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-x">
#           <path stroke="none" d="M0 0h24v24H0z" fill="none" />
#           <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
#           <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
#         </svg>
#       color: "#000"
#       link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
#     - name: "Facebook"
#       icon: "facebook"
#       color: "#3e569b"
#       link: "https://www.facebook.com/sharer/sharer.php?u=$URL"

# 打赏组件设置
donate:
  enable: true
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "https://dev.krt.moe/demo-assets/donate.webp"
  platforms:
    - name: "模拟支付"
      icon: "credit-card"
      color: "skyblue"
      qrcode: "example_payment"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at:
      - post
      - page
    template:
      _shared: <div class="kr-comments lazy-load"><div id="tcomment"></div></div>

# 访问数量统计
visit_count:
  enable_at: []
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ################## 
# <script src="/hc/effects/cursor-effects.js"></script>
additional_injections:
  head: |
    <link rel="stylesheet" href="https://unpkg.com/aplayer@1.10.1/dist/APlayer.min.css">
    <link rel="stylesheet" href="/hc/widgets/aplayer.css">
    <link rel="stylesheet" href="/hc/others/mobile-hero.css"/>
    <link rel="stylesheet" href="/hc/effects/snow.css" />
  footer: |
    <meting-js server="netease" type="playlist" id="60198" fixed="true"></meting-js>
    <canvas id="snow"></canvas>
  after_footer: |
    <script src="https://cdn.jsdelivr.net/npm/twikoo@1.6.39/dist/twikoo.all.min.js"></script>
    <script src="/hc/comments/twikoo.js"></script>
    <script src="https://unpkg.com/aplayer@1.10.1/dist/APlayer.min.js"></script>
    <script src="https://unpkg.com/meting@2.0.1/dist/Meting.min.js"></script>
    <script src="/hc/effects/leave-event.js"></script>
    <script src="/hc/others/random-post-cover.js"></script>
    <script src="/hc/effects/snow.js"></script>


