################## 系统配置 ##################

search:
  includes:
    - post
    - page

################## 样式配置 ##################

# 图片配置
image:
  favicon: "/assets/favicon.png" # 站点图标
  #avatar: "/assets/logo.webp" # 个人信息挂件上的头像
  banner:
    light: "https://dev.krt.moe/demo-assets/banner.webp"
    dark: "https://dev.krt.moe/demo-assets/banner_dark.webp"
  background:
    light: "https://dev.krt.moe/demo-assets/bg.webp"
    dark: "https://dev.krt.moe/demo-assets/bg.webp"

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 档案馆
      icon: file
      url: /archives/
    - label: 链接
      icon: link
      submenu:
        - label: 代码仓库
          icon: code
          url: https://github.com/Candinya/Kratos-Rebirth
        - label: 项目文档
          icon: book
          url: https://wiki.krt.moe

# Footer 页脚配置
footer:
  links:
    - icon: github
      link: https://github.com/kratos-rebirth
    - icon: rss
      link: /atom.xml
  components:
    uptime:
      since: "2018/05/06 17:03:12"
      text: "本站已在风雨中飘摇"
    author:
      homepage: "https://github.com/Candinya/Kratos-Rebirth/graphs/contributors"
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://github.io" target="_blank">Github Pages</a> 暖心托管

# 代码高亮
# syntax_highlighter:
#   theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "喵窝"
      html: <svg fill="currentColor" width="18" height="18" viewBox="0 0 329 388"><path d="M0,36.226c0,-19.993 16.233,-36.226 36.226,-36.226c13.788,0 25.787,7.719 31.908,19.068l188.366,229.845l0,-111.259c-6.356,5.508 -14.645,8.843 -23.707,8.843c-19.994,0 -36.226,-16.232 -36.226,-36.226c-0,-8.551 2.968,-16.413 7.93,-22.613l-0.015,-0.013l56.614,-69.08c6.2,-11.073 18.047,-18.565 31.63,-18.565c19.994,0 36.227,16.233 36.227,36.226l-0,314.644c-0,19.994 -16.233,36.226 -36.227,36.226c-13.166,0 -24.701,-7.039 -31.044,-17.555l-189.229,-230.899l-0,212.228c-0,19.994 -16.233,36.226 -36.227,36.226c-19.993,0 -36.226,-16.232 -36.226,-36.226l0,-314.644Z" /></svg>
      color: "#62b6e7"
      link: "https://nya.one/share?text=%3E%20$TITLE%0A%3E%0A%3E%20$SUMMARY%0A----%20$SITE%0A%0A$URL"

# 打赏组件设置
donate:
  enable: true
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "https://dev.krt.moe/demo-assets/donate.webp"
  platforms:
    - name: "模拟支付"
      icon: "credit-card"
      color: "skyblue"
      qrcode: "example_payment"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at:
    # - index
      - post
      - page
    template:
      _shared: ""
      index: ""
      post: ""
      page: ""
  count:
    enable_at: []
    # - index
    # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at: []
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: "" # 搜索引擎验证，或是追加的样式表
  footer: ""
  after_footer: "" # 站点分析，或是追加的脚本
